<!DOCTYPE html><html lang="en-us" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Jaehyeok Shin">

  
  
  
    
  
  <meta name="description" content="When comparing means of two non-negative random variables, we are often interested in the ratio of two means since the ratio does not depend on the scale of underlying distributions.">

  
  <link rel="alternate" hreflang="en-us" href="https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/">

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  

  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    

  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
    
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144639945-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'UA-144639945-1', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_huc50b28ae5ce84fcc767e7691e9c0c0ae_20181_32x32_fill_lanczos_center_3.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_huc50b28ae5ce84fcc767e7691e9c0c0ae_20181_192x192_fill_lanczos_center_3.png">

  <link rel="canonical" href="https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/">

  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@Project20s">
  <meta property="twitter:creator" content="@Project20s">
  
  <meta property="og:site_name" content="Jae&#39;s Blog">
  <meta property="og:url" content="https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/">
  <meta property="og:title" content="Sequential test for ratio of two means | Jae&#39;s Blog">
  <meta property="og:description" content="When comparing means of two non-negative random variables, we are often interested in the ratio of two means since the ratio does not depend on the scale of underlying distributions."><meta property="og:image" content="https://shinjaehyeok.github.io/images/icon_huc50b28ae5ce84fcc767e7691e9c0c0ae_20181_512x512_fill_lanczos_center_3.png">
  <meta property="twitter:image" content="https://shinjaehyeok.github.io/images/icon_huc50b28ae5ce84fcc767e7691e9c0c0ae_20181_512x512_fill_lanczos_center_3.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2024-01-24T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2024-01-24T00:00:00&#43;00:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/"
  },
  "headline": "Sequential test for ratio of two means",
  
  "datePublished": "2024-01-24T00:00:00Z",
  "dateModified": "2024-01-24T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Jaehyeok Shin"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Jae's Blog",
    "logo": {
      "@type": "ImageObject",
      "url": "https://shinjaehyeok.github.io/images/icon_huc50b28ae5ce84fcc767e7691e9c0c0ae_20181_192x192_fill_lanczos_center_3.png"
    }
  },
  "description": "When comparing means of two non-negative random variables, we are often interested in the ratio of two means since the ratio does not depend on the scale of underlying distributions."
}
</script>

  

  


  


  





  <title>Sequential test for ratio of two means | Jae&#39;s Blog</title>

</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class=" ">

  
  
  
    <script>window.staDarkLightChooser = true;</script>
  
  
    <script>const isSiteThemeDark = false;</script>
  
  
  <script src="/js/load-theme.js"></script>

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Jae&#39;s Blog</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Jae&#39;s Blog</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>



  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Sequential test for ratio of two means</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    Jan 24, 2024
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    5 min read
  </span>
  

  
  
  
  <span class="middot-divider"></span>
  <a href="/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/#disqus_thread"></a>
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/category/statistics/">Statistics</a></span>
  

</div>

    














  
</div>





  <div class="article-container">

    <div class="article-style">
      


<p>When comparing means of two non-negative random variables, we are often interested in the ratio of two means since the ratio does not depend on the scale of underlying distributions. A typical statistical test for the ratio of two means is based on either the ratio of two sample means or its logarithmic value.</p>
<p>For the fixed sample size case, by the delta method, the log ratio of two sample means can be approximated by a normal distribution. Therefore, we can build an asymptotically valid z-test or t-test for a large enough fixed sample size. Since the log ratio can be approximated by a normal distribution, it is natural to ask whether the sequential normal test can be applied to the sequence of logs of ratios too.</p>
<p>From the author’s best knowledge, the validity of the normal approximation in the sequential testing setup is not yet fully understood. As a practitioner, in this post, we simulate the type-1 error of the sequential normal test to examine whether we may practically use the sequential normal test to continuously monitor the ratio of two means.</p>
<p>Specifically, we will use a naive plug-in method of the following steps:</p>
<ol style="list-style-type: decimal">
<li>Estimate the variance of the log ratio of two sample means via the grouped jackknife method.</li>
<li>Naively treat the log ratio of sample means as an observed sample mean and apply a normal sequential test by plugging-in the variance estimate from the previous step.</li>
</ol>
<p>Before diving into the sequential test simulation, let’s first review the fixed sample size case.</p>
<div id="asymptotic-distribution-of-log-ratio-of-two-sample-means" class="section level1">
<h1>Asymptotic distribution of log ratio of two sample means</h1>
<pre class="r"><code>group_jackknife_variance_estimator &lt;- function(x_vec, y_vec, group_size = 20) {
  group_sum_helper &lt;- function(vec, group_ind) {
    sum(vec[seq_along(vec) %% group_size == group_ind])
  }
  x_grouped_sum &lt;- sapply(seq(0, group_size - 1), group_sum_helper, vec = x_vec)
  y_grouped_sum &lt;- sapply(seq(0, group_size - 1), group_sum_helper, vec = y_vec)
  
  x_sum &lt;- sum(x_vec)
  y_sum &lt;- sum(y_vec)
  
  log_total_ratio &lt;- log(y_sum / x_sum)
  
  loo_ratio_vec &lt;- (y_sum - y_grouped_sum) / (x_sum - x_grouped_sum)
  loo_log_ratio_vec &lt;- log(loo_ratio_vec)

  return(var(group_size * log_total_ratio - (group_size-1) * loo_log_ratio_vec) / (group_size))
}

group_jackknife_bias_corrected_estimator &lt;- function(x_vec, y_vec, group_size = 20) {
  group_sum_helper &lt;- function(vec, group_ind) {
    sum(vec[seq_along(vec) %% group_size == group_ind])
  }
  x_grouped_sum &lt;- sapply(seq(0, group_size - 1), group_sum_helper, vec = x_vec)
  y_grouped_sum &lt;- sapply(seq(0, group_size - 1), group_sum_helper, vec = y_vec)
  
  x_sum &lt;- sum(x_vec)
  y_sum &lt;- sum(y_vec)
  
  log_total_ratio &lt;- log(y_sum / x_sum)
  
  loo_ratio_vec &lt;- (y_sum - y_grouped_sum) / (x_sum - x_grouped_sum)
  loo_log_ratio_vec &lt;- log(loo_ratio_vec)

  return(group_size * log_total_ratio - (group_size - 1) * mean(loo_log_ratio_vec))
}

fixed_size_simulator &lt;- function(n, sig_x, sig_y, group_size = 20) {
  # We use log normal distribution logNormal(0, sig^2) for each group.
  x_vec &lt;- exp(rnorm(n, 0, sig_x))
  y_vec &lt;- exp(rnorm(n, 0, sig_y))
  
  log_sample_ratio &lt;- log(sum(y_vec) / sum(x_vec))
  bias_corrected &lt;- group_jackknife_bias_corrected_estimator(x_vec, y_vec, group_size)
  variance_estimate &lt;- group_jackknife_variance_estimator(x_vec, y_vec, group_size)
  
  out &lt;- c(
    log_sample_ratio = log_sample_ratio,
    bias_corrected = bias_corrected,
    variance_estimate = variance_estimate
  )
  
  return(out)
}

sequential_simulator &lt;- function(n, sig_x, sig_y, group_size = 20) {
  # We use log normal distribution logNormal(0, sig^2) for each group.
  x_vec &lt;- exp(rnorm(n, 0, sig_x))
  y_vec &lt;- exp(rnorm(n, 0, sig_y))
  
  # Compute a sequence of logs of ratios of sample means and their variances.
  log_sample_ratio_vec &lt;- log(cumsum(y_vec) / cumsum(x_vec))
  variance_estimator &lt;- function(i) {
    return(group_jackknife_variance_estimator(x_vec[1:i], y_vec[1:i], group_size))
  }
  
  variance_estimate_vec &lt;- sapply(seq_along(x_vec), variance_estimator)
  
  
  bias_corrected_estimator &lt;- function(i) {
    return( group_jackknife_bias_corrected_estimator(x_vec[1:i], y_vec[1:i], group_size))
  }
  
  bias_corrected_vec &lt;- sapply(seq_along(x_vec), bias_corrected_estimator)
  
  out &lt;- data.frame(
    log_sample_ratio = log_sample_ratio_vec,
    bias_corrected = bias_corrected_vec,
    variance_estimate = variance_estimate_vec
  )
  
  return(out)
}</code></pre>
<pre class="r"><code>set.seed(100)
alpha &lt;- 0.05
n_fixed &lt;- 200
b &lt;- 5000
sig_x &lt;- 1/2
sig_y &lt;- sig_x
group_size &lt;- 20

fixed_runs &lt;- replicate(b, fixed_size_simulator(n_fixed, sig_x, sig_y, group_size = group_size))
m_vec &lt;- fixed_runs[&quot;log_sample_ratio&quot;, ]
b_vec &lt;- fixed_runs[&quot;bias_corrected&quot;,]
s_vec &lt;- sqrt(fixed_runs[&quot;variance_estimate&quot;,])

hist(m_vec / s_vec, breaks = 20, prob=TRUE,
     main = &quot;Distribution of log ratio of sample means&quot;,
     xlab = &quot;log ratio of sample mean&quot;,
     ylim = c(0,0.4), xlim = c(-4,4))
curve(dnorm(x, mean=0, sd=1), 
      col=&quot;darkblue&quot;, lwd=2, add=TRUE, yaxt=&quot;n&quot;)
curve(dt(x, df = group_size - 1), 
      col=&quot;darkred&quot;, lwd=2, add=TRUE, yaxt=&quot;n&quot;)</code></pre>
<p><img src="/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means_files/figure-html/fixed%20sample-1.png" width="672" /></p>
<pre class="r"><code>hist(b_vec / s_vec, breaks = 20, prob=TRUE,
     main = &quot;Distribution of bias-corrected estimates&quot;,
     xlab = &quot; bias-corrected estimates&quot;,
     ylim = c(0,0.4), xlim = c(-4,4))
curve(dnorm(x, mean=0, sd=1), 
      col=&quot;darkblue&quot;, lwd=2, add=TRUE, yaxt=&quot;n&quot;)
curve(dt(x, df = group_size - 1), 
      col=&quot;darkred&quot;, lwd=2, add=TRUE, yaxt=&quot;n&quot;)</code></pre>
<p><img src="/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means_files/figure-html/fixed%20sample-2.png" width="672" />
In this simulation study, we generate two independent and identical groups of samples from the log normal distribution, logNormal(0, 1/2^2) of the size 200.
We repeat this simulation run for 5000 times.</p>
<p>Above, we plot histograms of simulated log ratios and their bias-corrected estimates normalized by the grouped Jackknife variance estimates with the group size of 20. freedom blue line corresponds to the density of the standard normal distribution and the red line is for the t-distribution with 19 degree of freedom. We can see the log ratio and its bias-corrected estimates are well-approximated by Normal and t-distributions.</p>
</div>
<div id="t-test-for-a-fixed-sample-size" class="section level1">
<h1>T-test for a fixed sample size</h1>
<pre class="r"><code>t_alpha_over_2 &lt;- qt(1-alpha / 2, df = group_size - 1)

t_test &lt;- function(m, s, alpha = 0.05){
  t_value &lt;- m/s
  is_rejected &lt;- abs(t_value) &gt; t_alpha_over_2
  return(ifelse(is.na(is_rejected), FALSE, is_rejected))
}

t_test_result &lt;- t_test(b_vec, s_vec)

print(&quot;Type-1 error is&quot;)</code></pre>
<pre><code>## [1] &quot;Type-1 error is&quot;</code></pre>
<pre class="r"><code>print(mean(t_test_result))</code></pre>
<pre><code>## [1] 0.0516</code></pre>
<p>Here, we run fixed sample size t-test of level 0.05 for 5000 times. As expected, t-test with Jackknife estimates controls the type-1 error at the target level.</p>
<div id="t-test-cannot-be-used-for-a-sequential-setup." class="section level2">
<h2>T-test cannot be used for a sequential setup.</h2>
<pre class="r"><code>n &lt;- 500 
sequential_runs &lt;- replicate(b, sequential_simulator(n, sig_x, sig_y, group_size = group_size))

m_list &lt;- sequential_runs[&quot;log_sample_ratio&quot;,]
b_list &lt;- sequential_runs[&quot;bias_corrected&quot;,]
s_list &lt;- lapply(sequential_runs[&quot;variance_estimate&quot;,], sqrt)

seq_t_test_for_each_run &lt;- function(ind, alpha = 0.05) {
  return(any(t_test(b_list[[ind]], s_list[[ind]], alpha)))
}

seq_t_test_result &lt;- sapply(1:b, seq_t_test_for_each_run, alpha = alpha)

print(&quot;Type-1 error is&quot;)</code></pre>
<pre><code>## [1] &quot;Type-1 error is&quot;</code></pre>
<pre class="r"><code>print(mean(seq_t_test_result))</code></pre>
<pre><code>## [1] 0.6186</code></pre>
<p>As same as the usual t-test, if we run t-test sequentially whenever a new data comes, type-1 error of the test significantly inflated and no longer control the error at the target level. Usually, sequential test is designed to run indefinitely and, from the law of the iterated logarithm, we know the type-1 error will go up to 1 eventually. For a sake of demonstration, we only run t-test sequentially up to 500 samples. However, at n = 500, the type-1 error already reached at 0.6186, which is significantly higher than the target level 0.05.</p>
</div>
</div>
<div id="sequential-normal-test-with-jackknife-variance-estimate." class="section level1">
<h1>Sequential normal test with Jackknife variance estimate.</h1>
<pre class="r"><code>library(stcpR6)

log_ratio_lower &lt;- 0.01
log_ratio_upper &lt;- 0.1

st_normal &lt;- stcpR6::Stcp$new(
  method = &quot;ST&quot;,
  family = &quot;Normal&quot;,
  alternative = &quot;two.sided&quot;,
  threshold = log(1/alpha), # level alpha test
  m_pre = 0,  # Null: log ratio = 0
  delta_lower = log_ratio_lower, # Lower bound of the size of log ratio
  delta_upper = log_ratio_upper  # Upper bound of the size of log ratio
)

# Note the upper and low bounds do not affect the validity of the testing procedure.
# It only affects the sample efficiency under the alternative.

st_normal_test_for_each_run &lt;- function(ind, alpha = 0.05) {
 
  # We start the test after group_size samples.
  
  # 1/variance estimates.
  n_cumsum &lt;- (1/s_list[[ind]]^2)[-seq(1,group_size)]
  # Get an incremental 1/variance estimate of each time by taking the diff
  n_vec &lt;- c(n_cumsum[1], n_cumsum[-1] - n_cumsum[-length(n_cumsum)])
  # Set 0 if we have no meaningful variance estimate.
  n_vec[is.nan(n_vec)|is.na(n_vec)] &lt;- 0

  # Get cumulative sum process by multiplying bias-corrected estimates and 1/variances.    
  s_cumsum &lt;- b_list[[ind]][-seq(1,group_size)] * n_cumsum
  # Get an incremental sum process.
  s_vec &lt;- c(s_cumsum[1], s_cumsum[-1] - s_cumsum[-length(s_cumsum)])
  # Compute the normalized incremental process.
  b_vec &lt;- s_vec / n_vec
  # Set 0 if we have no meaningful estimate.
  b_vec[is.nan(b_vec)|is.na(b_vec)] &lt;- 0
 
  # Initialize stcp object to start sequential test
  st_normal$reset()
  # Run the sequential test by naively treating
  # the normalized incremental process as sample mean
  # and the 1/variance process as the true 1/variance process.
  st_normal$updateLogValuesUntilStopByAvgs(
    x_bars = b_vec,
    ns = n_vec
  )
    
  return(st_normal$isStopped())
}

st_normal_test_result &lt;- sapply(1:b, 
                                st_normal_test_for_each_run,
                                alpha)

print(&quot;Type-1 error is&quot;)</code></pre>
<pre><code>## [1] &quot;Type-1 error is&quot;</code></pre>
<pre class="r"><code>print(mean(st_normal_test_result))</code></pre>
<pre><code>## [1] 0.0324</code></pre>
<p>To evaluate the type-1 error of the sequential normal test with variance estimates, we used <a href="https://github.com/shinjaehyeok/stcpR6"><code>stcpR6</code></a> package supporting various sequential testing and change-point detection algorithms. In this simulation, we use the sequential normal test setup designed to detect log ratio of two means with the size between [0.01, 0.1] effectively under the alternative.</p>
<p>Originally, this sequential test object is designed to take the sample mean and the reciprocal of its true variance at each time to decide whether it should reject the null or not. Instead, in this simulation, we put the bias-corrected estimate and the reciprocal of the estimated variance as naive proxies.</p>
<p>Unlike the t-test example above, this sequential normal test with Jackknife variance estimate results in the type-1 error of 0.032, which is under the target level even after 500 samples. It would be interesting to see whether the type-1 error keep remaining below the target level as the number of sample size increase but for the sake of time, we only run the simulation up to 500 samples.</p>
</div>
<div id="comparison-of-powers-of-tests" class="section level1">
<h1>Comparison of powers of tests</h1>
<pre class="r"><code>set.seed(100)
b &lt;- 5000
sig_x &lt;- 1/2
sig_y_under_h1 &lt;- 1/10

fixed_runs_under_h1 &lt;- replicate(b, fixed_size_simulator(
  n_fixed, 
  sig_x, 
  sig_y_under_h1, 
  group_size))

b_vec_under_h1 &lt;- fixed_runs_under_h1[&quot;bias_corrected&quot;,]
s_vec_under_h1 &lt;- sqrt(fixed_runs_under_h1[&quot;variance_estimate&quot;,])</code></pre>
<p>So far, we study the validity of t-test and sequential normal test for log ratio of two means via simulations. Especially, we checked that the sequential normal test with Jackknife bias-corrected estimates and variance estimates seems to control the type-1 error, at least in this specific simulation setup.</p>
<pre class="r"><code>t_test_result_under_h1 &lt;- t_test(b_vec_under_h1, s_vec_under_h1)

print(&quot;Power of the t-test is&quot;)</code></pre>
<pre><code>## [1] &quot;Power of the t-test is&quot;</code></pre>
<pre class="r"><code>print(mean(t_test_result_under_h1))</code></pre>
<pre><code>## [1] 0.8558</code></pre>
<p>Now, it is natural to ask whether the sequential normal test is sample-efficient under alternatives. As a reference, we simulate the power of the fixed sample size t-test. For the alternative scenario, We picked logNormal(0, 1/2^2) and logNormal(0, 1/3^2) distributions and compared log ratio of two means. The true log ratio of two means is given by -0.069. With the fixed sample size of 200, the power of the fixed sample t-test is given by 0.856.</p>
<pre class="r"><code>sequential_runs_under_h1 &lt;- replicate(b, sequential_simulator(n, sig_x, sig_y_under_h1, group_size = group_size))

b_list_under_h1 &lt;- sequential_runs_under_h1[&quot;bias_corrected&quot;,]
s_list_under_h1 &lt;- lapply(sequential_runs_under_h1[&quot;variance_estimate&quot;,], sqrt)</code></pre>
<p>For the sequential normal case, ideally, we need to run the each simulation until the null hypothesis is rejected since the sequential test is designed to be a power of 1 test, and its efficiency is measured by the expected stopping time under the alternative.</p>
<pre class="r"><code>st_normal &lt;- stcpR6::Stcp$new(
  method = &quot;ST&quot;,
  family = &quot;Normal&quot;,
  alternative = &quot;two.sided&quot;,
  threshold = log(1/alpha), # level alpha test
  m_pre = 0,  # Null: log ratio = 0
  delta_lower = log_ratio_lower, # Lower bound of the size of log ratio
  delta_upper = log_ratio_upper  # Upper bound of the size of log ratio
)

st_normal_test_for_each_run_under_h1 &lt;- function(ind, alpha = 0.05) {
 
  # We start the test after group_size samples.
  
  # 1/variance estimates.
  n_cumsum &lt;- (1/s_list_under_h1[[ind]]^2)[-seq(1,group_size)]
  # Get an incremental 1/variance estimate of each time by taking the diff
  n_vec &lt;- c(n_cumsum[1], n_cumsum[-1] - n_cumsum[-length(n_cumsum)])
  # Set 0 if we have no meaningful variance estimate.
  n_vec[is.nan(n_vec)|is.na(n_vec)] &lt;- 0

  # Get cumulative sum process by multiplying bias-corrected estimates and 1/variances.    
  s_cumsum &lt;- b_list_under_h1[[ind]][-seq(1,group_size)] * n_cumsum
  # Get an incremental sum process.
  s_vec &lt;- c(s_cumsum[1], s_cumsum[-1] - s_cumsum[-length(s_cumsum)])
  # Compute the normalized incremental process.
  b_vec &lt;- s_vec / n_vec
  # Set 0 if we have no meaningful estimate.
  b_vec[is.nan(b_vec)|is.na(b_vec)] &lt;- 0
 
  # Initialize stcp object to start sequential test
  st_normal$reset()
  # Run the sequential test by naively treating
  # the normalized incremental process as sample mean
  # and the 1/variance process as the true 1/variance process.
  st_normal$updateLogValuesUntilStopByAvgs(
    x_bars = b_vec,
    ns = n_vec
  )
  
  stopped_time &lt;- which(abs(st_normal$getStoppedTime() - n_cumsum) &lt; 1e-8)
    
  return(c(
    stopped_time = ifelse(length(stopped_time) == 0, n, max(stopped_time)),
    is_stopped = st_normal$isStopped()
    )
  )
}


st_normal_test_result_under_h1  &lt;- sapply(1:b, 
                                          st_normal_test_for_each_run_under_h1, 
                                          alpha)
stopped_time &lt;- st_normal_test_result_under_h1[&quot;stopped_time&quot;, ]
is_stopped &lt;- st_normal_test_result_under_h1[&quot;is_stopped&quot;, ]
print(&quot;Power of the test and average stopped time are&quot;)</code></pre>
<pre><code>## [1] &quot;Power of the test and average stopped time are&quot;</code></pre>
<pre class="r"><code>print(c(mean(is_stopped), mean(stopped_time)))</code></pre>
<pre><code>## [1]   0.9772 195.0054</code></pre>
<p>For the sake of simple simulation, we run the each simulation only up to 500 samples as same as the previous type-1 error simulation case. Then, we measure both the power of the sequential normal test up to the horizon 500 and the average of the stopped time. From the simulation, we observed that the sequential normal test achieved a higher power 0.98 while the average of the stopped time 195.01 is lower than the fixed sample size 200 of the previous t-test simulation.</p>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>In this post, we reviewed the validity and effectiveness of the fixed sample size t-test for testing log ratio of two means via grouped Jackknife estimates. Then we explored whether we can use the sequential normal test with grouped Jackknife estimates to build a valid and effective sequential testing process. Although there is no formal proof of the validity, the simulation showed, at this the logNormal two sample testing case, the sequential normal test resulted in a valid type-1 error control and yielded a high power and sample efficiency under the alternative.</p>
</div>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/ab-test/">ab test</a>
  
  <a class="badge badge-light" href="/tag/inference/">inference</a>
  
  <a class="badge badge-light" href="/tag/sequential-test/">sequential test</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/&amp;text=Sequential%20test%20for%20ratio%20of%20two%20means" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/&amp;t=Sequential%20test%20for%20ratio%20of%20two%20means" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Sequential%20test%20for%20ratio%20of%20two%20means&amp;body=https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://shinjaehyeok.github.io/post/statistics/sequential_test_for_ratio_of_means/sequential_test_for_ratio_of_means/&amp;title=Sequential%20test%20for%20ratio%20of%20two%20means" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
  </ul>
</div>












  
  





  
    
    
    
      
    
    
    
    <div class="media author-card content-widget-hr">
      
        
        <img class="avatar mr-3 avatar-circle" src="/author/jaehyeok-shin/avatar_hu4bfebfed29c68355e919404572255097_130697_270x270_fill_q90_lanczos_center.jpg" alt="Jaehyeok Shin">
      

      <div class="media-body">
        <h5 class="card-title"><a href="https://shinjaehyeok.github.io/">Jaehyeok Shin</a></h5>
        <h6 class="card-subtitle">Data Scientist</h6>
        <p class="card-text">Interested in understanding the sequential and adaptive nature of data analysis.</p>
        <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/#contact" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/Project20s" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.com/citations?user=9vx2IdMAAAAJ" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/jh-shin/" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
</ul>

      </div>
    </div>
  







<section id="comments">
  
    
<div id="disqus_thread"></div>
<script>
  let disqus_config = function () {
    
    
    
  };
  (function() {
    if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
      document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
      return;
    }
    var d = document, s = d.createElement('script'); s.async = true;
    s.src = 'https://' + "shinjaehyeok" + '.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


  
</section>








  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/statistics/sequential_test_safety/sequential_test_flexibility_safety/">Advantages of Sequential Hypothesis Testing: 2. Flexibility and Safety</a></li>
      
      <li><a href="/post/statistics/sequential_test_efficiency/stcd-tutorial/">Advantages of Sequential Hypothesis Testing: 1. Sample efficiency</a></li>
      
      <li><a href="/post/statistics/change_detection/from_seq_test_to_change_detection/">From Sequential Tests to Change Detections</a></li>
      
    </ul>
  </div>
  





  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js" integrity="sha512-7t8APmYpzEsZP7CYoA7RfMPV9Bb+PJHa9x2WiUnDXZx3XHveuyWUtvNOexhkierl5flZ3tr92dP1mMS+SGlD+A==" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/languages/latex.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    <script id="dsq-count-scr" src="https://shinjaehyeok.disqus.com/count.js" async></script>
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.e286f7f9ceb21a7a7468a7eb9912703f.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    Copyright 2024 Jaehyeok Shin. All rights reserved.
  </p>

  
  








 
  <script>
  $(document).ready(function () {
    window.initializeCodeFolding("show" === "hide");
  });
  </script>
  <script src="/js/codefolding.js"></script>



  <p class="powered-by">
    
    Published with
    <a href="https://wowchemy.com" target="_blank" rel="noopener">Wowchemy Website Builder</a>
    

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
